### Import the functions written in the query_helper.py file

In [1]:
!pip install psycopg2

Collecting psycopg2
  Using cached psycopg2-2.7.3-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: psycopg2
Successfully installed psycopg2-2.7.3
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [2]:
import psycopg2 as pg2
import pandas as pd

### Write Functions to Query from the Tables Created

In [3]:
import pandas as pd
import psycopg2 as pg2
from psycopg2.extras import RealDictCursor

def connect_to_db():
    con = pg2.connect(host='postgres', dbname='postgres', user='postgres')
    cur = con.cursor(cursor_factory=RealDictCursor)
    return con, cur

def query_to_dictionary(query, fetch_res=True):
    con, cur = connect_to_db()
    cur.execute(query)
    if fetch_res:
        results = cur.fetchall()
    else:
        results = None
    con.close()
    return results

def query_to_dataframe(query):
    return pd.DataFrame(query_to_dictionary(query))

In [4]:
connect_to_db()

(<connection object at 0x7f0305c2f048; dsn: 'host=postgres dbname=postgres user=postgres', closed: 0>,
 <cursor object at 0x7f0304bbde48; closed: 0>)

### Insert content into the created tables (which are currently empty)

In [5]:
con, cur = connect_to_db()

In [6]:
# define function to pass in category_name and category_id

def insert_category (id_no, name):
    '''
    grab category names and ids and push into the postsql db
    '''
    connect_to_db()
    con, cur = connect_to_db()
    
    query = '''
            BEGIN;
            INSERT INTO category VALUES ({}, '{}');
            COMMIT;
            '''.format(id_no, name)
    
    cur.execute(query)

In [7]:
CATEGORY_df = pd.read_pickle('../data/CATEGORY_df.p')

In [8]:
CATEGORY_df.reset_index(inplace=True, drop=True)

In [9]:
CATEGORY_df.head()

                              category  categoryid
0            Category:Machine_learning          43
1    Category:Applied machine learning           1
2  Category:Artificial neural networks           3
3           Category:Bayesian networks           4
4   Category:Classification algorithms          12

In [10]:
CATEGORY_df.iloc[0, 1]

43

In [11]:
cur.execute("SELECT * FROM category LIMIT 1")

In [12]:
for i in CATEGORY_df.index:
    insert_category(CATEGORY_df.iloc[i,1], CATEGORY_df.iloc[i,0])

In [14]:
query = '''
SELECT * 
FROM category
'''

query_to_dataframe(query)

    cid                                               name
0    43                          Category:Machine_learning
1     1                  Category:Applied machine learning
2     3                Category:Artificial neural networks
3     4                         Category:Bayesian networks
4    12                 Category:Classification algorithms
5    13                          Category:Cluster analysis
6    15             Category:Computational learning theory
7     2       Category:Artificial intelligence conferences
8    16  Category:Data mining and machine learning soft...
9    17              Category:Datasets in machine learning
10   19                       Category:Dimension reduction
11   21                         Category:Ensemble learning
12   23                   Category:Evolutionary algorithms
13   26                       Category:Genetic programming
14   30               Category:Inductive logic programming
15   33       Category:Kernel methods for machine learning
16   34                    Category:Latent variable models
17   35               Category:Learning in computer vision
18   36                         Category:Log-linear models
19   37                            Category:Loss functions
20   39               Category:Machine learning algorithms
21   40                   Category:Machine learning portal
22   42                     Category:Machine learning task
23   46                             Category:Markov models
24   41              Category:Machine learning researchers
25   54                   Category:Semisupervised learning
26   56   Category:Statistical natural language processing
27   57                     Category:Structured prediction
28   58                       Category:Supervised learning
29   59                   Category:Support vector machines
..  ...                                                ...
34    6               Category:Business software companies
35    7               Category:Business software for Linux
36    8               Category:Business software for MacOS
37    9             Category:Business software for Windows
38   14                    Category:Collaborative software
39   18       Category:Dental practice management software
40   22                       Category:Enterprise software
41   20                              Category:ERP software
42   24                        Category:Financial software
43   25                    Category:Free business software
44   27                           Category:Health software
45   28                       Category:Healthcare software
46   29        Category:Human resource management software
47   32                  Category:Java enterprise platform
48   44                    Category:Manufacturing software
49   45                        Category:Marketing software
50   38                              Category:MES software
51   47                  Category:Mobile business software
52   48                           Category:Office software
53   49                           Category:Portal software
54   50               Category:Project management software
55   51                       Category:Publishing software
56   52                        Category:Reporting software
57   53                  Category:Risk management software
58   55  Category:Service-oriented architecture-related...
59   60                              Category:Tax software
60   61        Category:Telecommunications Billing Systems
61   63                       Category:Workflow technology
62   31     Category:Industry-specific XML-based standards
63   10                   Category:Business software stubs

[64 rows x 2 columns]

In [15]:
def insert_page (id_no, title, text):
    '''
    grab page ids, titles, and text, and then push into the postsql db
    '''
    connect_to_db()
    con, cur = connect_to_db()
    
    query = '''
            BEGIN;
            INSERT INTO page VALUES ({}, '{}', '{}');
            COMMIT;
            '''.format(id_no, title, text)
    
    cur.execute(query)

In [37]:
PAGE_df = pd.read_pickle('../data/PAGE_df.p')

In [38]:
PAGE_df.head()

,pageid,title,text
0,54972729,User:CustIntelMngt/sandbox/Customer Intelligen...,this is not a wikipedia article it is an indiv...
1,43385931,Data exploration,this article has multiple issues please help i...
2,49082762,List of datasets for machine learning research,machine learning anddata miningproblemsclassif...
3,233488,Machine learning,for the journal see machine learning journal m...
4,53587467,Outline of machine learning,the following outline is provided as an overvi...

In [39]:
PAGE_df[PAGE_df['pageid'] == 405562]

,pageid,title,text
170,405562,Solomonoff's theory of inductive inference,this article has multiple issues please help i...

In [23]:
# because i applied the cleaner to the text and not the title, I will now apply text_cleaner to the titles as well
# hopefully this won't cause issues

In [40]:
import re

In [41]:
def text_cleaner(text):
    text = re.sub('[\.]',' ',text)
    text = re.sub('[\']', '', text)
    text = re.sub('([^A-Za-z0-9_])\W+',' ', text)
    text = re.sub('\W',' ',text.lower())
    text = re.sub('\d','', text)
    return text

In [44]:
PAGE_df['title'] = PAGE_df['title'].apply(lambda x: text_cleaner(x))

In [45]:
PAGE_df[PAGE_df['pageid'] == 405562]

,pageid,title,text
170,405562,solomonoff s theory of inductive inference,this article has multiple issues please help i...

In [46]:
PAGE_df.head()

,pageid,title,text
0,54972729,user custintelmngt sandbox customer intelligen...,this is not a wikipedia article it is an indiv...
1,43385931,data exploration,this article has multiple issues please help i...
2,49082762,list of datasets for machine learning research,machine learning anddata miningproblemsclassif...
3,233488,machine learning,for the journal see machine learning journal m...
4,53587467,outline of machine learning,the following outline is provided as an overvi...

In [51]:
PAGE_df.head()

,pageid,title,text
0,54972729,user custintelmngt sandbox customer intelligen...,this is not a wikipedia article it is an indiv...
1,43385931,data exploration,this article has multiple issues please help i...
2,49082762,list of datasets for machine learning research,machine learning anddata miningproblemsclassif...
3,233488,machine learning,for the journal see machine learning journal m...
4,53587467,outline of machine learning,the following outline is provided as an overvi...

In [52]:
for i in PAGE_df.index:
    insert_page(PAGE_df.iloc[i,0], PAGE_df.iloc[i,1], PAGE_df.iloc[i,2])

In [53]:
query = '''
SELECT * 
FROM page
'''

query_to_dataframe(query)

,pid,text,title
0,54972729,this is not a wikipedia article it is an indiv...,user custintelmngt sandbox customer intelligen...
1,43385931,this article has multiple issues please help i...,data exploration
2,49082762,machine learning anddata miningproblemsclassif...,list of datasets for machine learning research
3,233488,for the journal see machine learning journal m...,machine learning
4,53587467,the following outline is provided as an overvi...,outline of machine learning
5,3771060,the accuracy paradox for predictive analytics ...,accuracy paradox
6,43808044,machine learning anddata miningproblemsclassif...,action model learning
7,28801798,this article is about a machine learning metho...,active learning machine learning
8,45049676,adversarial machine learning is a research fie...,adversarial machine learning
9,52642349,aivanationalityluxembourgishstyleclassical mus...,aiva
10,30511763,this article has multiple issues please help i...,aixi
11,50773876,this article is an orphan as no other articles...,algorithm selection
12,20890511,algorithmic inference gathers new developments...,algorithmic inference
13,49242352,alphago logoalphago is a narrow ai computer pr...,alphago
14,19463198,apprenticeship learning or apprenticeship via ...,apprenticeship learning
15,14003441,for bag of words model in computer vision see ...,bag of words model
16,31877832,this article is about the binary tree variant ...,ball tree
17,9732182,this article needs additional citations for ve...,base rate
18,35867897,this article provides insufficient context for...,bayesian interpretation of kernel regularization
19,40973765,bayesian optimization is a sequential design s...,bayesian optimization
20,50211107,this article includes a list of references but...,bayesian structural time series
21,40678189,this article needs additional citations for ve...,bias variance tradeoff
22,205393,this article needs additional citations for ve...,binary classification
23,50646178,the topic of this article may not meet wikiped...,bing predicts
24,1191936,an example bongard problem the common factor o...,bongard problem
25,44439173,the bradley terry model is a probability model...,bradley terry model
26,53631046,caffeoriginal author s yangqing jiadeveloper s...,caffe software
27,39182554,this article has multiple issues please help i...,catastrophic interference
28,8964665,category utility is a measure of category good...,category utility
29,17114678,the center for biological computational learni...,cbcl mit
...,...,...,...
2757,5649998,office automation refers to the varied compute...,office automation
2758,4991466,for the term other government agency see oga o...,office genuine advantage
2759,9788607,the topic of this article may not meet wikiped...,omgeo
2760,25034980,openmeetingsdeveloper s maxim solodovnik sebas...,openmeetings
2761,3069932,this article needs additional citations for ve...,perform
2762,4767593,this article contains content that is written ...,pivot chart
2763,3062614,screenshot of plan runningplan is a calendar a...,plan calendar program
2764,456424,postscript printer descriptionfilename extensi...,postscript printer description
2765,18532395,this article is about the project management s...,project kickstart
2766,15530023,qfxfilename extension qfxdeveloped byintuitcon...,qfx file format
2767,48254824,reflex was a d building design software applic...,reflex building design software
2768,2438634,this article needs additional citations for ve...,sage accounting
2769,9636465,this article has multiple issues please help i...,salary calculator
2770,19539906,this article is an orphan as no other articles...,sap transport management system
2771,327999,sasi schools administrative student informatio...,sasi software
2772,26723213,sentinel is a software case management system ...,sentinel fbi
2773,26178912,this article needs additional citations for ve...,sierra chart
2774,48253668,sonata was a d building design software applic...,sonata building design software
2775,14569194,sprogstable release july operating systemcro...,sprog software
2776,47534615,super decisionsindustrycomputer softwarefounde...,super decisions
2777,1966364,supercalcsupercalc for ms dos developer s sorc...,supercalc
2778,5192200,taurus transfer and automated registration of ...,taurus share settlement
2779,1131405,this article needs additional citations for ve...,tress
2780,8838142,ibm unica netinsightdeveloper s ibminitial rel...,ibm unica netinsight
2781,9818995,this article does not cite any sources please ...,wang office
2782,51567252,this article has multiple issues please help i...,weworked
2783,5794691,this article is about the computer term for th...,whiteboarding
2784,50315118,the topic of this article may not meet wikiped...,workflowy
2785,3234557,the r internally called xcon for expert config...,xcon
2786,4260606,this article has multiple issues please help i...,xdb enterprise server

In [23]:
# REVISIT LATER!
# df.apply(lambda x: insert_category(x.name, x.cid), axis=1)
# look at documentation for lambda and axes to quadruple check, for my own edification also

# CATEGORY_df

NameError: name 'category' is not defined

In [55]:
total_df = pd.read_pickle('../data/total_df.p')

In [57]:
from sklearn.preprocessing import LabelEncoder

In [59]:
total_df.head()

,ns,pageid,title,category,text
0,2,54972729,User:CustIntelMngt/sandbox/Customer Intelligen...,Category:Machine_learning,this is not a wikipedia article it is an indiv...
1,0,43385931,Data exploration,Category:Machine_learning,this article has multiple issues please help i...
2,0,49082762,List of datasets for machine learning research,Category:Machine_learning,machine learning anddata miningproblemsclassif...
3,0,233488,Machine learning,Category:Machine_learning,for the journal see machine learning journal m...
4,0,53587467,Outline of machine learning,Category:Machine_learning,the following outline is provided as an overvi...

In [63]:
le = LabelEncoder()

In [64]:
total_df['category_id'] = le.fit_transform(total_df['category'])

In [67]:
total_df.drop('ns', axis=1, inplace=True)

In [68]:
total_df.head()

,pageid,title,category,text,category_id
0,54972729,User:CustIntelMngt/sandbox/Customer Intelligen...,Category:Machine_learning,this is not a wikipedia article it is an indiv...,43
1,43385931,Data exploration,Category:Machine_learning,this article has multiple issues please help i...,43
2,49082762,List of datasets for machine learning research,Category:Machine_learning,machine learning anddata miningproblemsclassif...,43
3,233488,Machine learning,Category:Machine_learning,for the journal see machine learning journal m...,43
4,53587467,Outline of machine learning,Category:Machine_learning,the following outline is provided as an overvi...,43

In [79]:
CATEGORY_PAGE_df = total_df[['pageid', 'category_id']]

In [80]:
CATEGORY_PAGE_df.shape

(2787, 2)

In [81]:
CATEGORY_PAGE_df.columns

Index(['pageid', 'category_id'], dtype='object')

In [93]:
def insert_category_page (page_id, category_id):
    con, cur = connect_to_db()
    
    query = '''
    BEGIN;
    INSERT INTO category_page VALUES ('{}', '{}');
    COMMIT;
    '''.format(page_id, category_id)
    
    cur.execute(query)

In [90]:
CATEGORY_PAGE_df.iloc[0, 1]

43

In [94]:
for i in CATEGORY_PAGE_df.index:
    insert_category_page(CATEGORY_PAGE_df.iloc[i,0], CATEGORY_PAGE_df.iloc[i,1])

In [98]:
query = '''
SELECT *
FROM category_page
'''

query_to_dataframe(query)

      category_cid  page_pid
0               43  54972729
1               43  43385931
2               43  49082762
3               43    233488
4               43  53587467
5               43   3771060
6               43  43808044
7               43  28801798
8               43  45049676
9               43  52642349
10              43  30511763
11              43  50773876
12              43  20890511
13              43  49242352
14              43  19463198
15              43  14003441
16              43  31877832
17              43   9732182
18              43  35867897
19              43  40973765
20              43  50211107
21              43  40678189
22              43    205393
23              43  50646178
24              43   1191936
25              43  44439173
26              43  53631046
27              43  39182554
28              43   8964665
29              43  17114678
...            ...       ...
2757            10   9788607
2758            10  25034980
2759            10   1699107
2760            10   3069932
2761            10   4767593
2762            10   3062614
2763            10    456424
2764            10  18532395
2765            10  15530023
2766            10  48254824
2767            10  22628313
2768            10   2438634
2769            10   9636465
2770            10  19539906
2771            10    327999
2772            10  26723213
2773            10  26178912
2774            10  48253668
2775            10  14569194
2776            10  47534615
2777            10   1966364
2778            10   5192200
2779            10   1131405
2780            10   8838142
2781            10   9818995
2782            10  51567252
2783            10   5794691
2784            10  50315118
2785            10   3234557
2786            10   4260606

[2787 rows x 2 columns]